export const UPDATE_CARTCOUNT = 'UPDATE_CARTCOUNT'

export const UPDATE_USERINFO = 'UPDATE_USERINFO'

export const UPDATE_SEARCH_HISTORY = 'UPDATE_SEARCH_HISTORY'


export const UPDATE_LOGIN_FLAG = 'UPDATE_LOGIN_FLAG'